environment:
  global:
    PROJECT_NAME: nightly_cmd_fail
    nodejs_version: "6"
  matrix:
    # Stable channel
    - TARGET: i686-pc-windows-msvc
      RUST_CHANNEL: stable
    # Nightly channel
    - TARGET: i686-pc-windows-msvc
      RUST_CHANNEL: nightly

# Install Rust and Cargo
install:
  - ps: Install-Product node $env:nodejs_version
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/channel-rust-stable"
  - ps: $env:RUST_VERSION = Get-Content channel-rust-stable | select -first 1 | %{$_.split('-')[1]}
  - if NOT "%RUST_CHANNEL%" == "stable" set RUST_VERSION=%RUST_CHANNEL%
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:RUST_VERSION}-${env:TARGET}.exe"
  - rust-%RUST_VERSION%-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -V
  - cargo -V
  - node --version
  - npm --version
  - npm install -g stylus nib
  - npm -g list

build: false

# Equivalent to Travis' `script` phase
test_script:
    #- cargo run --verbose
    - rustc src\main.rs
    - main.exe

branches:
  only:
    - master
